# Generated by Django 4.1.2 on 2022-11-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_experian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='describtion',
            new_name='detial',
        ),
        migrations.AddField(
            model_name='profile',
            name='selfExplain',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
