# Generated by Django 4.1.2 on 2022-11-09 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='where',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Webapp.profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ratting',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
