# Generated by Django 4.1.2 on 2022-12-09 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0005_comment_where_alter_comment_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name_plural': ['comment']},
        ),
    ]
