# Generated by Django 4.1.2 on 2024-02-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='selfExplain',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
